const SPACE_SET_DISPLAY_NAMES = Object.freeze({
  'horizon-sequence-05-women-top-draped': '부드러운 조명의 호리존 스튜디오',
  'horizon-sequence-06-women-top-linen': '맑고 담백한 호리존 스튜디오',
  'horizon-sequence-07-men-top-pleated': '차분한 조명의 호리존 스튜디오',
  'horizon-sequence-08-men-top-textured': '선명한 질감의 호리존 스튜디오',
  'horizon-sequence-09-women-dress-knit': '포근한 조명의 호리존 스튜디오',
  'set-women-bottom-rainy-storefront-kclub-140072876': '비 오는 상점 앞',
  'set-women-bottom-urban-ggsing-140741411': '낡은 상가 앞 골목',
  'set-women-bottom-home-petrichoor-162619101': '따뜻한 작은 집',
  'set-women-bottom-beach-nissome-133330805': '맑은 한낮의 해변',
  'set-style-women-dress-botanical-attrangs-160835-root01': '초록빛 보태니컬 리조트',
  'set-style-women-dress-city-ivy-modimood-2928-root02': '담쟁이 덮인 도심 골목',
  'set-style-women-dress-cafe-garden-attrangs-160544-root03': '볕 드는 카페 정원',
  'set-style-women-dress-neighborhood-garage-modimood-3266-root04': '생활감 있는 주택 골목',
  'set-style-women-dress-coast-beach-hotping-48001-root05': '작은 해변과 항구',
  'set-style-women-dress-home-living-musinsa-6570399-root06': '밝고 편안한 거실',
  'set-style-women-dress-night-riverwalk-maybins-40948-root07': '불빛 비치는 강변 산책로',
  'set_style_women_top_indoor_attrangs_170129_prod01': '따뜻한 실내 작업실',
  'set_style_women_top_outdoor_slowand_10690_prod01': '햇살 드는 시장 골목',
  'set_style_women_outer_indoor_commonunique_26096_prod01': '밝은 렌털 아틀리에',
  'set_style_women_top_cafe_attrangs_170103_prod02': '작은 카페와 상점',
  'set_style_women_top_home_hotping_48041_prod02': '차분한 중성색 거실',
  'set_style_women_top_urban_creamcheese_26667_prod02': '회색빛 도심 외벽',
  'set_style_women_outer_storefront_lowclassic_6495851_prod02': '조용한 서점 앞',
  'set_style_women_top_park_realcoco_161014511_prod02': '햇살 좋은 잔디 공원',
  'set_style_women_top_coast_sinoon_6575707_prod02': '탁 트인 해안 산책로',
  'set_style_women_outer_terrace_lowclassic_6495831_prod02': '느긋한 리조트 테라스',
  'set_style_women_top_convenience_beidelli_5067_prod03': '동네 편의점 앞',
  'set_style_women_outer_rainy_courtyard_nearwear_12582_prod03': '비 젖은 세탁소 안뜰',
  'set_style_women_outer_loadingzone_beidelli_3920_prod03': '지하 주차장 로딩존',
  'set-01-women-bottom-street-slowand-10666': '도심 골목의 거리 풍경',
  'set-03-women-dress-bright-interior-hotping-47530': '햇빛 밝은 실내',
  'set-01-women-bottom-home-undervi-22793': '부드러운 자연광의 창가',
  'set-04-women-bottom-street-slowand-10563': '동네 상점 앞 거리',
  'set-06-women-bottom-corridor-musinsa-6495795': '오래된 건물의 창가 복도',
  'set-07-women-bottom-riverside-bbibbongunni-22538': '흐린 날의 강변 산책로',
  'set-08-women-bottom-library-musinsa-6661117': '햇살 드는 동네 도서관',
  'set-01-men-top-indoor-retro-counter-byslim-28625': '정겨운 동네 카운터',
  'set-02-men-top-indoor-concrete-byslim-28635': '차분한 콘크리트 공간',
  'set-03-men-outer-outdoor-garden-byslim-28570': '햇빛 드는 정원길',
  'set-04-men-top-indoor-window-room-anotheroffice-1881': '볕 드는 작은 원룸',
  'set-05-men-common-outdoor-grey-wall-lockerroom-23701': '낮의 회색 외벽',
  'set-06-men-common-outdoor-quiet-alley-jogunshop-32115': '조용한 도심 보도',
  'set-07-men-top-indoor-small-shop-upnormal-7126': '작은 카페와 생활 매장',
  'set-08-men-top-outdoor-coast-ordercloset-2396': '바다와 항구 방파제',
  'set-09-men-outer-outdoor-resort-upnormal-7100': '햇살 좋은 풀 테라스',
  'set-10-men-outer-indoor-passage-lockerroom-23651': '고요한 건물 계단',
  'set-11-men-outer-outdoor-community-steps-gopeople-7214': '햇빛 비치는 외부 계단',
  'set-12-men-common-indoor-reading-corner-gopeople-7896': '동네 헌책방 독서 코너',
  'set-14-men-top-indoor-late-night-laundromat-lookple-8966': '불빛 따뜻한 심야 세탁실',
  'set-01-indoor': '은은한 조명의 실내',
  'set-02-street': '편안한 동네 거리',
  'set-03-resort': '여유로운 리조트 테라스',
  'set-04-living': '차분한 거실과 원룸',
  'set-05-cafe': '볕 드는 카페와 매장',
  'set-08-park': '초록빛 공원 산책길',
  'set-09-coast': '탁 트인 해안 보도',
  'set-10-night': '불빛 번지는 저녁 도심',
  'set-13-sports-center': '햇빛 드는 체육관 계단',
  'set-14-car-wash': '선명한 조명의 셀프 세차장',
  'set_horizon_women_bottom_threetimes_7563033280596_prod01': '균일한 조명의 회전 스튜디오',
  'set_horizon_men_bottom_hatchingroom_2161_prod01': '선명한 조명의 회전 스튜디오',
  'horizon-set-01-women-scarf-outer': '부드러운 톤의 호리존 스튜디오',
  'horizon-set-02-women-fluid-trousers': '움직임이 돋보이는 호리존 스튜디오',
  'horizon-set-03-men-tonal-outer': '차분한 톤온톤 스튜디오',
  'horizon-set-04-men-chino-focus': '담백한 조명의 호리존 스튜디오',
});

const FALLBACK_BY_PLACE = Object.freeze({
  'atelier-interior': '따뜻한 실내 작업실',
  'building-interior': '밝은 실내 세트',
  'cafe-shop-interior': '볕 드는 카페 세트',
  'home-interior': '편안한 거실 세트',
  'horizon-studio': '밝은 호리존 스튜디오',
  'industrial-yard': '도시적인 야외 세트',
  'library-interior': '조용한 서재 세트',
  'park-garden': '초록빛 정원 세트',
  'resort-terrace': '여유로운 테라스 세트',
  'service-interior': '생활감 있는 실내 세트',
  'storefront-street': '동네 상점 앞 세트',
  'urban-alley': '차분한 도심 골목',
  'urban-building-exterior': '도시적인 건물 외벽',
  waterfront: '탁 트인 물가 산책로',
});

export function spaceSetDisplayName(set) {
  return SPACE_SET_DISPLAY_NAMES[set?.id]
    || FALLBACK_BY_PLACE[set?.placeType]
    || (set?.setType?.startsWith('horizon') ? '밝은 호리존 스튜디오' : '실내 촬영 세트');
}

export function mappedSpaceSetCount() {
  return Object.keys(SPACE_SET_DISPLAY_NAMES).length;
}
