/* =============================================================
   lib/types.js — Type boundary (ported from handoff/contracts/types.js)
   Pure shape definitions + closed enum catalogs. No data, no UI.
   The mock layer (mock/) produces values that conform to these;
   when a real backend lands it must return these same shapes.

   NOTE (TS adoption): when we migrate this file to .ts, align the
   typedefs to mock/db.js — db carries fields the original typedef
   lagged on: Analysis.suggestedName, MatchClothing.selOrder, and
   the auto-block kinds 'size'|'care'|'ai-notice' (BlockKind is
   non-exhaustive for auto blocks). [user decision 2026-06-09]
   ============================================================= */

/* ---- Closed enums (the union types referenced in JSDoc) ---- */
export const ClothingType = Object.freeze({ TOP: 'top', BOTTOM: 'bottom', OUTER: 'outer', DRESS: 'dress' });
export const Gender = Object.freeze({ WOMEN: 'women', MEN: 'men' });
export const Fit = Object.freeze({ SLIM: 'slim', REGULAR: 'regular', SEMI_OVER: 'semi_over', OVER: 'over' });
export const ComposeMode = Object.freeze({ SIMPLE: 'simple', BASIC: 'basic', EXTENDED: 'extended' });
export const BlockKind = Object.freeze({ HOOK: 'hook', SELLING: 'selling', STYLING: 'styling', HORIZON: 'horizon', PRODUCT: 'product', INFO: 'info' });
export const Direction = Object.freeze({ FRONT: 'front', BACK: 'back', SIDE: 'side' });
export const ShotType = Object.freeze({ FULL: 'full', KNEE: 'knee', MEDIUM: 'medium', CLOSE: 'close' });
export const CutSource = Object.freeze({ STUDIO: 'studio', DAILY: 'daily', PRODUCT: 'product', MINE: 'mine' });
export const JobStatus = Object.freeze({ IDLE: 'idle', RUNNING: 'running', DONE: 'done', ERROR: 'error' });
export const ElementType = Object.freeze({ IMAGE: 'image', TEXT: 'text', SHAPE: 'shape', LINE: 'line' });
export const AngleSlot = Object.freeze({ FRONT: 'Front', BACK: 'Back', DETAIL: 'Detail', FIT: 'Fit' });

/* =============================================================
   JSDoc shapes (kept verbatim from the contract)
   -------------------------------------------------------------
   @typedef {Object} ImageAsset
   @property {string} id
   @property {string} src            data-uri or url (placeholder for now)
   @property {string} [label]        e.g. "Front", "정면"
   @property {string} [slot]         AngleSlot for color-1 reference shots
   @property {boolean} [ai]          generated by AI vs uploaded

   @typedef {Object} ColorGroup
   @property {string} id
   @property {string} name           color name, AI-estimated or user
   @property {boolean} isBase        색상 1 = base/reference color
   @property {boolean} [isMain]      chosen as a main color
   @property {boolean} [monotone]    black/white/ivory/cream/gray/charcoal/beige
   @property {ImageAsset[]} images

   @typedef {Object} Measurement
   @property {string} key            e.g. "총장"
   @property {string} label
   @property {number|null} value     cm, null if blank
   @property {string} unit

   @typedef {Object} Material
   @property {string} name           e.g. "코튼"
   @property {number} ratio          percent

   @typedef {Object} ProductInput
   @property {string} id
   @property {string} name
   @property {ClothingType} clothingType
   @property {ColorGroup[]} colors
   @property {Measurement[]} measurements
   @property {boolean} measurementsUnknown
   @property {boolean} uploadComplete

   @typedef {Object} Analysis
   @property {ClothingType} clothingType
   @property {string} subCategory
   @property {Gender[]} targetGenders
   @property {Fit} fit
   @property {Material[]} materials
   @property {string[]} sellingPoints       user tags (max 5)
   @property {string[]} aiSuggestedPoints   AI-discovered (max 2)
   @property {string} selectedModelId
   @property {Model[]} models
   @property {MatchClothing[]} matchClothing
   @property {string} washCare
   @property {boolean} locked
   @property {string} [suggestedName]       db carries this (typedef lagged)

   @typedef {Object} Model
   @property {string} id
   @property {string} name
   @property {string} thumb
   @property {boolean} recommended

   @typedef {Object} MatchClothing
   @property {string} id
   @property {string} name
   @property {string} thumb
   @property {boolean} selected
   @property {number} [selOrder]            1=메인, 2=서브 (db carries this)

   @typedef {Object} MannequinCut
   @property {string} id              e.g. "A-0"
   @property {'A'|'B'} candidate
   @property {number} version
   @property {string} src
   @property {string} fitLabel        e.g. "정핏"
   @property {string} lengthLabel     e.g. "원본 기장"
   @property {boolean} selected

   @typedef {Object} StoryboardBlock
   @property {string} id
   @property {BlockKind} kind
   @property {string} title
   @property {Direction} [direction]
   @property {ShotType} [shot]
   @property {string} [colorId]
   @property {string} thumb
   @property {string} poseThumb
   @property {string} poseLabel
   @property {string} bgThumb        보존 필드 — 콘티 UI에는 노출 안 함 (PRD §8.5)
   @property {string} bgLabel        보존 필드 — 콘티 UI에는 노출 안 함 (PRD §8.5)
   @property {CutSource} source

   @typedef {Object} Element
   @property {string} id
   @property {ElementType} type
   @property {number} x @property {number} y
   @property {number} w @property {number} h
   @property {number} [rotate]
   @property {number} [radius]
   @property {number} [opacity]
   @property {string} [src]
   @property {string} [text]
   @property {Object} [style]
   @property {string} [shape]

   @typedef {Object} Block
   @property {string} id
   @property {string} name
   @property {string} kind            BlockKind | 'size'|'care'|'ai-notice' (auto)
   @property {string} bg
   @property {Element[]} elements
   @property {boolean} [auto]

   @typedef {Object} GenStep
   @property {string} key
   @property {string} label
   @property {JobStatus} status

   @typedef {Object} GenJob
   @property {number} progress
   @property {GenStep[]} steps
   @property {BlockKind[]} composition

   @typedef {Object} LibraryItem
   @property {string} id
   @property {string} title
   @property {string} cover
   @property {ClothingType} clothingType
   @property {number} blocks
   @property {'draft'|'generating'|'done'} status
   @property {string} updatedAt

   @typedef {Object} Account
   @property {string} name
   @property {string} avatar
   @property {number} credits
   @property {'Free'|'Pro'|'Team'} plan
   ============================================================= */

/** Convenience namespace mirroring the prototype's window.WT */
export const WT = Object.freeze({
  ClothingType, Gender, Fit, ComposeMode, BlockKind, Direction,
  ShotType, CutSource, JobStatus, ElementType, AngleSlot,
});

export default WT;
