spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/issuer
    username: ${OPENDID_DB_USER}
    password: ${OPENDID_DB_PASSWORD}
blockchain:
  file-path: /opt/opendid/secrets/Issuer/blockchain.properties
setup:
  base-url: http://127.0.0.1
  path: /opt/opendid/jars
tas:
  url: http://127.0.0.1:8090
wallet:
  file-path: /opt/opendid/secrets/Issuer/issuer.wallet
  password: ${OPENDID_ISSUER_WALLET_PASSWORD}
zkp-wallet:
  file-path: /opt/opendid/secrets/Issuer/issuer.zkpwallet
  password: ${OPENDID_ISSUER_ZKP_WALLET_PASSWORD}
