/* =============================================================
   Wearless — Type boundary (types/)
   Pure shape definitions + closed enum catalogs. No data, no UI.
   Mock layer (mock/) produces values that conform to these.
   When the real backend lands, it must return these same shapes.
   JS can't enforce types, so this file is the contract + the
   single source of truth for the small "union" enums.
   ============================================================= */

/* ---- Closed enums (the union types referenced in JSDoc) ---- */
const ClothingType = Object.freeze({ TOP: 'top', BOTTOM: 'bottom', OUTER: 'outer', DRESS: 'dress' });
const Gender       = Object.freeze({ WOMEN: 'women', MEN: 'men' });
const Fit          = Object.freeze({ SLIM: 'slim', REGULAR: 'regular', SEMI_OVER: 'semi_over', OVER: 'over' });
const ComposeMode  = Object.freeze({ SIMPLE: 'simple', BASIC: 'basic', EXTENDED: 'extended' });
const BlockKind    = Object.freeze({ HOOK: 'hook', SELLING: 'selling', STYLING: 'styling', HORIZON: 'horizon', PRODUCT: 'product', INFO: 'info' });
const Direction    = Object.freeze({ FRONT: 'front', BACK: 'back', SIDE: 'side' });
const ShotType     = Object.freeze({ FULL: 'full', KNEE: 'knee', MEDIUM: 'medium', CLOSE: 'close' });
const CutSource    = Object.freeze({ STUDIO: 'studio', DAILY: 'daily', PRODUCT: 'product', MINE: 'mine' });
const JobStatus    = Object.freeze({ IDLE: 'idle', RUNNING: 'running', DONE: 'done', ERROR: 'error' });
const ElementType  = Object.freeze({ IMAGE: 'image', TEXT: 'text', SHAPE: 'shape', LINE: 'line' });
const AngleSlot    = Object.freeze({ FRONT: 'Front', BACK: 'Back', DETAIL: 'Detail', FIT: 'Fit' });

/* =============================================================
   JSDoc shapes
   -------------------------------------------------------------
   @typedef {Object} ImageAsset
   @property {string} id
   @property {string} src            data-uri or url (placeholder for now)
   @property {string} [label]        e.g. "Front", "정면"
   @property {string} [slot]         AngleSlot for color-1 reference shots
   @property {boolean} [ai]          generated by AI vs uploaded

   @typedef {Object} ColorGroup
   @property {string} id
   @property {string} name           color name, AI-estimated or user
   @property {boolean} isBase         색상 1 = base/reference color
   @property {boolean} [isMain]       chosen as a main color
   @property {boolean} [monotone]     black/white/ivory/cream/gray/charcoal/beige
   @property {ImageAsset[]} images

   @typedef {Object} Measurement
   @property {string} key            e.g. "총장"
   @property {string} label
   @property {number|null} value     cm, null if blank
   @property {string} unit

   @typedef {Object} Material
   @property {string} name           e.g. "코튼"
   @property {number} ratio          percent

   @typedef {Object} ProductInput
   @property {string} id
   @property {string} name
   @property {ClothingType} clothingType
   @property {ColorGroup[]} colors
   @property {Measurement[]} measurements
   @property {boolean} measurementsUnknown
   @property {boolean} uploadComplete

   @typedef {Object} Analysis
   @property {ClothingType} clothingType
   @property {string} subCategory
   @property {Gender[]} targetGenders
   @property {Fit} fit
   @property {Material[]} materials
   @property {string[]} sellingPoints       user tags (max 5)
   @property {string[]} aiSuggestedPoints    AI-discovered (max 2)
   @property {string} selectedModelId
   @property {Model[]} models
   @property {MatchClothing[]} matchClothing
   @property {string} washCare
   @property {boolean} locked

   @typedef {Object} Model
   @property {string} id
   @property {string} name
   @property {string} thumb
   @property {boolean} recommended

   @typedef {Object} MatchClothing
   @property {string} id
   @property {string} name
   @property {string} thumb
   @property {boolean} selected

   @typedef {Object} MannequinCut
   @property {string} id              e.g. "A-0"
   @property {'A'|'B'} candidate
   @property {number} version
   @property {string} src
   @property {string} fitLabel        e.g. "정핏"
   @property {string} lengthLabel     e.g. "원본 기장"
   @property {boolean} selected

   @typedef {Object} StoryboardBlock
   @property {string} id
   @property {BlockKind} kind
   @property {string} title
   @property {Direction} [direction]
   @property {ShotType} [shot]
   @property {string} [colorId]
   @property {string} thumb
   @property {string} poseThumb
   @property {string} poseLabel
   @property {string} bgThumb
   @property {string} bgLabel
   @property {CutSource} source

   @typedef {Object} Element             상세페이지 선택요소
   @property {string} id
   @property {ElementType} type
   @property {number} x @property {number} y
   @property {number} w @property {number} h
   @property {number} [rotate]
   @property {number} [radius]
   @property {number} [opacity]
   @property {string} [src]            for image
   @property {string} [text]          for text
   @property {Object} [style]          text/shape styling
   @property {string} [shape]          circle|rect|triangle|line

   @typedef {Object} Block               에디터 블록 (width 1000px)
   @property {string} id
   @property {string} name
   @property {BlockKind} kind
   @property {string} bg
   @property {Element[]} elements

   @typedef {Object} GenStep
   @property {string} key
   @property {string} label
   @property {JobStatus} status

   @typedef {Object} GenJob
   @property {number} progress         0..100
   @property {GenStep[]} steps
   @property {BlockKind[]} composition

   @typedef {Object} LibraryItem
   @property {string} id
   @property {string} title
   @property {string} cover
   @property {ClothingType} clothingType
   @property {number} blocks
   @property {'draft'|'generating'|'done'} status
   @property {string} updatedAt

   @typedef {Object} Account
   @property {string} name
   @property {string} avatar
   @property {number} credits
   @property {'Free'|'Pro'|'Team'} plan
   ============================================================= */

window.WT = Object.freeze({
  ClothingType, Gender, Fit, ComposeMode, BlockKind, Direction,
  ShotType, CutSource, JobStatus, ElementType, AngleSlot,
});
